version: "3.4"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 5173:5173
      - 3000:3000
      - 24678:24678
    volumes:
      - $PWD:/home/node/app